#!/usr/bin/env python

Import("env")
Import("env_modules")

env_move = env_modules.Clone()
env_move.Prepend(CPPPATH=["."])

# Godot's own source files
env_move.add_source_files(env.modules_sources, "*.cpp")
